project:
  type: manuscript
  resources: 
    - "Tabelle_Item_Antwort_Aehnlichkeiten.html"
    - "Tabelle_Item_Antwort_Aehnlichkeiten_files/"

manuscript:
  article: index.qmd
  notebooks:
    - notebook: _notebooks/sample_size_sufficiency_analysis.qmd
      title: Sample Size Sufficiency Analysis
    - notebook: _notebooks/word_embeddings.qmd
      title: Word Embeddings
  meca-bundle: false

format:
  html:
    comments:
      hypothesis: false
    number-sections: false
  apaquarto-docx: default

execute:
  freeze: auto





