project:
  type: manuscript

manuscript:
  article: index.qmd
  notebooks:
    - notebook: _notebooks/sample_size_sufficiency_analysis.qmd
      title: Sample Size Sufficiency Analysis
    - notebook: _notebooks/word_embeddings.qmd
      title: Word Embeddings
  meca-bundle: false

format:
  html:
    comments:
      hypothesis: false
  apaquarto-docx: default
  pdf: default

execute:
  freeze: auto





